version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:delegated
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:delegated
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:delegated
      - ${NGINX_LOG_DIR}:/var/log/nginx/:delegated
    restart: always
    networks:
      - default
    environment: 
      - TZ=Asia/Shanghai  

  php72:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_XDEBUG: ${PHP72_XDEBUG}
        PHP_SWOOLE: ${PHP72_SWOOLE}
        PHP_REDIS: ${PHP72_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    container_name: php72
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:delegated
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:delegated
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:delegated
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
    ports:
      - "${RPC_SERVER_PORT}:9090"
    environment: 
      - TZ=Asia/Shanghai

  # php56:
  #   build:
  #     context: .
  #     args:
  #       PHP_VERSION: ${PHP56_VERSION}
  #       PHP_XDEBUG: ${PHP56_XDEBUG}
  #       PHP_SWOOLE: ${PHP56_SWOOLE}
  #       PHP_REDIS: ${PHP56_REDIS}
  #       REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
  #   volumes:
  #     - ${SOURCE_DIR}:/var/www/html/:delegated
  #     - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:delegated
  #     - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:delegated
  #   restart: always
  #   cap_add:
  #     - SYS_PTRACE
  #   networks:
  #     - default
  #   ports:
  #     - "${RPC_SERVER_PORT_56}:9091"

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    container_name: mysql
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:delegated
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:delegated
    restart: always
    networks:
      default:
        ipv4_address: ${MYSQL_IPV4}
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      
     

  redis:
    image: bitnami/redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - default
    volumes:
      - ${REDIS_DATA_DIR}:/bitnami/redis/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
#    container_name: elasticsearch
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - TZ=Asia/Shanghai
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ${ES_DATA}:/usr/share/elasticsearch/data:delegated
#    ports:
#      - 9200:9200
#    networks:
#      - default
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ${ES_DATA}:/usr/share/elasticsearch/data:delegated
  #   networks:
  #     - default

#  beanstalkd:
#    image: schickling/beanstalkd
#    container_name: beanstalkd
#    ports:
#      - "${BEANSTALKD_PORT}:11300"
#    restart: always
#    networks:
#      - default
#    environment:
#      - TZ=Asia/Shanghai
#
#  mongodb:
#    image: 'bitnami/mongodb:${MONGODB_VERSION}'
#    container_name: mongodb
#    ports:
#      - "${MONGODB_HOST_PORT}:27017"
#    volumes:
#    - ${MONGODB_DATA_DIR}:/data/db:delegated
#    networks:
#      - default
#
#  debian:
#    image: 'debian:latest'
#    container_name: beanstalkd

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "${PHPMYADMIN_HOST_PORT}:80"
  #   networks:
  #     - default
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_PORT=3306

  # phpredisadmin:
  #   image: erikdubbelboer/phpredisadmin:latest
  #   ports:
  #     - "${REDISMYADMIN_HOST_PORT}:80"
  #   networks:
  #     - default
  #   environment:
  #     - REDIS_1_HOST=redis
  #     - REDIS_1_PORT=6379

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.1/16
         
